"""Generates the protobuf and gRPC modules the client is built on.

Run from anywhere: ``python scripts/generate_proto.py``. Reads the ``.proto`` files from the
reactor's ``proto`` module and writes Python modules into ``src/cyrock_db/_proto``.

Two things here are not boilerplate.

**Import rewriting.** ``protoc`` emits ``import cyrock_db_value_pb2 as ...`` for a sibling proto,
which resolves only if the output directory is on ``sys.path``. Ours is a package inside another
package, so every such import is rewritten to a relative one. Without this the generated modules
import fine when run from their own directory and fail everywhere else, which is the kind of bug
that surfaces first in a user's virtualenv.

**The version checks.** Generated code stamps in the minimum ``protobuf`` and ``grpcio`` runtimes
it will load under, and both refuse a runtime older than the code. This is the same trap
``protobuf.gencode.version`` guards on the Java side (root ``pom.xml``, issue #281): the generator
version is the floor every consumer inherits, so it is pinned and asserted rather than picked up
from whatever ``pip`` resolved this month.

**On the protobuf numbering.** The Java floor reads ``4.31.1`` and the Python one ``6.31.1``, and
they are the same protobuf release - 31.1. Protobuf versions its language runtimes on separate major
lines: ``protobuf-java`` 4.31.1 and the ``protobuf`` PyPI package 6.31.1 ship from that one release.
Python has no 4.31.1 at all - its 4.x line ended at 4.25.9 - so copying the Java number across
produces a requirement that cannot resolve. ``grpcio-tools==1.74.0`` is pinned because it is the
generator that stamps 6.31.1, keeping both SDKs on one protobuf release.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

CLIENT_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT   = CLIENT_ROOT.parent
PROTO_DIR   = REPO_ROOT / "proto" / "src" / "main" / "proto"
OUT_DIR     = CLIENT_ROOT / "src" / "cyrock_db" / "_proto"
VERSION_FILE = CLIENT_ROOT / "src" / "cyrock_db" / "_version.py"
ROOT_POM     = REPO_ROOT / "pom.xml"

# The floors pyproject.toml promises consumers. Generated code may not require more than these.
# Raising either means raising it in pyproject.toml in the same commit.
PROTOBUF_FLOOR = (6, 31, 1)   # protobuf release 31.1, the same release as protobuf-java 4.31.1
GRPCIO_FLOOR   = "1.74.0"

# `import cyrock_db_value_pb2 as cyrock__db__value__pb2` -> `from . import ...`, and the same for
# the _pb2_grpc modules. Anchored at line start so a match inside a docstring or string is left alone.
_ABSOLUTE_IMPORT = re.compile(r"^import (cyrock_db_\w+_pb2(?:_grpc)?) as (\w+)$", re.MULTILINE)


def _as_version(text: str) -> tuple[int, ...]:
    return tuple(int(part) for part in text.split("."))


def _maven_version() -> str:
    """The reactor's version, from the root pom.

    Read rather than duplicated so ``cyrock-db`` and ``cyrock-db-client-java`` cannot drift: they are
    released together and a consumer comparing the two should not have to wonder.

    The first ``<version>`` in the pom is the project's own; the ones after it belong to plugins and
    dependencies, so this deliberately takes only the first.
    """
    match = re.search(r"<version>([^<]+)</version>", ROOT_POM.read_text())
    if match is None:
        raise ValueError(f"No <version> found in {ROOT_POM}")
    return match[1].strip()


def _pep440(maven_version: str) -> str:
    """Maven's version spelling translated to Python's.

    Maven's ``-SNAPSHOT`` means "in development, before this version"; PEP 440 spells that
    ``.devN``. Without the translation ``pip`` reads ``1.0.0-SNAPSHOT`` as a local-version segment on
    a released ``1.0.0``, which orders *after* the real release rather than before it.
    """
    if maven_version.endswith("-SNAPSHOT"):
        return maven_version.removesuffix("-SNAPSHOT") + ".dev0"
    return maven_version


def _write_version() -> str:
    version = _pep440(_maven_version())
    VERSION_FILE.write_text(
        '"""The package version, derived from the reactor\'s root pom.xml.\n\n'
        "Generated by scripts/generate_proto.py - do not edit. See _maven_version there for why it is\n"
        'read rather than duplicated.\n"""\n\n'
        f'__version__ = "{version}"\n'
    )
    return version


def _generated_protobuf_floor(sample: Path) -> tuple[int, int, int] | None:
    """The minimum protobuf runtime protoc stamped into a generated module, if it declares one."""
    match = re.search(
        r"runtime_version\.ValidateProtobufRuntimeVersion\(\s*[^,]+,\s*(\d+),\s*(\d+),\s*(\d+),",
        sample.read_text(),
    )
    return (int(match[1]), int(match[2]), int(match[3])) if match else None


def _generated_grpc_floor(sample: Path) -> str | None:
    """The minimum grpcio runtime protoc stamped into a generated gRPC module, if it declares one."""
    match = re.search(r"^GRPC_GENERATED_VERSION = '([^']+)'", sample.read_text(), re.MULTILINE)
    return match[1] if match else None


def _rewrite_imports(path: Path) -> None:
    original = path.read_text()
    rewritten = _ABSOLUTE_IMPORT.sub(r"from . import \1 as \2", original)
    if rewritten != original:
        path.write_text(rewritten)


def main() -> int:
    if not PROTO_DIR.is_dir():
        # A git install has no reactor beside it; the release build ships _proto/ pre-generated.
        print(f"No proto sources at {PROTO_DIR}.", file=sys.stderr)
        print("This script runs inside the cyrock.db repository; a published copy ships _proto/ already.",
              file=sys.stderr)
        return 1

    protos = sorted(PROTO_DIR.glob("*.proto"))
    if not protos:
        print(f"No .proto files in {PROTO_DIR}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in list(OUT_DIR.glob("*_pb2.py")) + list(OUT_DIR.glob("*_pb2_grpc.py")) + list(OUT_DIR.glob("*.pyi")):
        stale.unlink()

    result = subprocess.run(
        [
            sys.executable, "-m", "grpc_tools.protoc",
            f"--proto_path={PROTO_DIR}",
            f"--python_out={OUT_DIR}",
            f"--pyi_out={OUT_DIR}",
            f"--grpc_python_out={OUT_DIR}",
            *(str(proto) for proto in protos),
        ],
        check=False,
    )
    if result.returncode != 0:
        return result.returncode

    for generated in list(OUT_DIR.glob("*_pb2.py")) + list(OUT_DIR.glob("*_pb2_grpc.py")):
        _rewrite_imports(generated)

    (OUT_DIR / "__init__.py").write_text(
        '"""Generated protobuf and gRPC modules. Not a public API - regenerate, never edit."""\n'
    )

    protobuf_floor = _generated_protobuf_floor(OUT_DIR / "cyrock_db_value_pb2.py")
    if protobuf_floor is not None and protobuf_floor > PROTOBUF_FLOOR:
        print(
            f"Generated code requires protobuf >= {'.'.join(map(str, protobuf_floor))}, but pyproject.toml "
            f"promises >= {'.'.join(map(str, PROTOBUF_FLOOR))}. Pin an older grpcio-tools, or raise both "
            f"together - the generator version is the floor every consumer inherits.",
            file=sys.stderr,
        )
        return 1

    grpc_floor = _generated_grpc_floor(OUT_DIR / "cyrock_db_value_pb2_grpc.py")
    if grpc_floor is not None and _as_version(grpc_floor) > _as_version(GRPCIO_FLOOR):
        print(
            f"Generated code requires grpcio >= {grpc_floor}, but pyproject.toml promises >= {GRPCIO_FLOOR}.",
            file=sys.stderr,
        )
        return 1

    version = _write_version()
    print(f"Generated {len(protos)} proto files into {OUT_DIR.relative_to(CLIENT_ROOT)}, version {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
