"""The package version, derived from the reactor's root pom.xml.

Generated by scripts/generate_proto.py - do not edit. See _maven_version there for why it is
read rather than duplicated.
"""

__version__ = "0.9.1"
