# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyrock_db_graph_pb2 as cyrock__db__graph__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cyrock_db_graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphGrpcServiceStub(object):
    """─── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNode = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetNode',
                request_serializer=cyrock__db__graph__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.GetEdge = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetEdge',
                request_serializer=cyrock__db__graph__pb2.GetEdgeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetEdgeResponse.FromString,
                _registered_method=True)
        self.AddNode = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/AddNode',
                request_serializer=cyrock__db__graph__pb2.AddNodeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.AddNodeResponse.FromString,
                _registered_method=True)
        self.AddEdge = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/AddEdge',
                request_serializer=cyrock__db__graph__pb2.AddEdgeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.AddEdgeResponse.FromString,
                _registered_method=True)
        self.RemoveNode = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/RemoveNode',
                request_serializer=cyrock__db__graph__pb2.RemoveNodeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.RemoveEdge = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/RemoveEdge',
                request_serializer=cyrock__db__graph__pb2.RemoveEdgeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.UpdateVector = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/UpdateVector',
                request_serializer=cyrock__db__graph__pb2.UpdateVectorRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.UpdateWeight = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/UpdateWeight',
                request_serializer=cyrock__db__graph__pb2.UpdateWeightRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.UpdateNodeMetadata = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/UpdateNodeMetadata',
                request_serializer=cyrock__db__graph__pb2.UpdateNodeMetadataRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.UpdateEdgeMetadata = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/UpdateEdgeMetadata',
                request_serializer=cyrock__db__graph__pb2.UpdateEdgeMetadataRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/ListNodes',
                request_serializer=cyrock__db__graph__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.ListLabels = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/ListLabels',
                request_serializer=cyrock__db__graph__pb2.ListLabelsRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.ListLabelsResponse.FromString,
                _registered_method=True)
        self.SearchSimilar = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/SearchSimilar',
                request_serializer=cyrock__db__graph__pb2.SearchSimilarRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.SearchSimilarResponse.FromString,
                _registered_method=True)
        self.Neighbors = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/Neighbors',
                request_serializer=cyrock__db__graph__pb2.NeighborsRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.NeighborsResponse.FromString,
                _registered_method=True)
        self.BatchNeighbors = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/BatchNeighbors',
                request_serializer=cyrock__db__graph__pb2.BatchNeighborsRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.BatchNeighborsResponse.FromString,
                _registered_method=True)
        self.Traverse = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/Traverse',
                request_serializer=cyrock__db__graph__pb2.TraverseRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.TraverseResponse.FromString,
                _registered_method=True)
        self.ContextWindow = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/ContextWindow',
                request_serializer=cyrock__db__graph__pb2.ContextWindowRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.ContextWindowResponse.FromString,
                _registered_method=True)
        self.ReasoningChain = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/ReasoningChain',
                request_serializer=cyrock__db__graph__pb2.ReasoningChainRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.ReasoningChainResponse.FromString,
                _registered_method=True)
        self.DetectCommunities = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/DetectCommunities',
                request_serializer=cyrock__db__graph__pb2.DetectCommunitiesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.DetectCommunitiesResponse.FromString,
                _registered_method=True)
        self.PutCommunitySummaries = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/PutCommunitySummaries',
                request_serializer=cyrock__db__graph__pb2.PutCommunitySummariesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.PutCommunitySummariesResponse.FromString,
                _registered_method=True)
        self.GlobalSearch = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GlobalSearch',
                request_serializer=cyrock__db__graph__pb2.GlobalSearchRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GlobalSearchResponse.FromString,
                _registered_method=True)
        self.RefreshCommunities = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/RefreshCommunities',
                request_serializer=cyrock__db__graph__pb2.DetectCommunitiesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.RefreshCommunitiesResponse.FromString,
                _registered_method=True)
        self.CommunityStatus = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/CommunityStatus',
                request_serializer=cyrock__db__graph__pb2.CommunityStatusRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.CommunityStatusResponse.FromString,
                _registered_method=True)
        self.GetCommunities = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunities',
                request_serializer=cyrock__db__graph__pb2.GetCommunitiesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.DetectCommunitiesResponse.FromString,
                _registered_method=True)
        self.GetCommunityMembers = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunityMembers',
                request_serializer=cyrock__db__graph__pb2.GetCommunityMembersRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetCommunityMembersResponse.FromString,
                _registered_method=True)
        self.GetCommunityAssignments = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunityAssignments',
                request_serializer=cyrock__db__graph__pb2.GetCommunityAssignmentsRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetCommunityAssignmentsResponse.FromString,
                _registered_method=True)
        self.GetCommunitySummaries = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunitySummaries',
                request_serializer=cyrock__db__graph__pb2.GetCommunitySummariesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetCommunitySummariesResponse.FromString,
                _registered_method=True)
        self.EntityLink = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/EntityLink',
                request_serializer=cyrock__db__graph__pb2.EntityLinkRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.EntityLinkResponse.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/Observe',
                request_serializer=cyrock__db__graph__pb2.ObserveRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.ObserveResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/Recall',
                request_serializer=cyrock__db__graph__pb2.RecallRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Decay = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/Decay',
                request_serializer=cyrock__db__graph__pb2.DecayRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.DecayResponse.FromString,
                _registered_method=True)
        self.ExecuteStatement = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/ExecuteStatement',
                request_serializer=cyrock__db__graph__pb2.ExecuteStatementRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.StatementResponse.FromString,
                _registered_method=True)
        self.MergeData = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/MergeData',
                request_serializer=cyrock__db__graph__pb2.MergeGraphDataRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.MergeGraphDataResponse.FromString,
                _registered_method=True)
        self.ExecuteTransaction = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/ExecuteTransaction',
                request_serializer=cyrock__db__graph__pb2.ExecuteTransactionRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.ExecuteTransactionResponse.FromString,
                _registered_method=True)
        self.UpsertNode = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/UpsertNode',
                request_serializer=cyrock__db__graph__pb2.UpsertNodeRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.UpsertNodeResponse.FromString,
                _registered_method=True)
        self.GetNodeByKey = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetNodeByKey',
                request_serializer=cyrock__db__graph__pb2.GetNodeByKeyRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.RemoveNodeByKey = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/RemoveNodeByKey',
                request_serializer=cyrock__db__graph__pb2.RemoveNodeByKeyRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GraphEmpty.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/GetNodes',
                request_serializer=cyrock__db__graph__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.GetNodesResponse.FromString,
                _registered_method=True)
        self.InducedSubgraph = channel.unary_unary(
                '/ai.cyrock.db.data.server.GraphGrpcService/InducedSubgraph',
                request_serializer=cyrock__db__graph__pb2.InducedSubgraphRequest.SerializeToString,
                response_deserializer=cyrock__db__graph__pb2.InducedSubgraphResponse.FromString,
                _registered_method=True)


class GraphGrpcServiceServicer(object):
    """─── Service ───────────────────────────────────────────────────────────────────

    """

    def GetNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveEdge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNodeMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEdgeMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLabels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Neighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Traverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContextWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReasoningChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectCommunities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutCommunitySummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshCommunities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommunityStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunityMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunityAssignments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunitySummaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EntityLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStatement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeByKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNodeByKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InducedSubgraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=cyrock__db__graph__pb2.GetNodeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetNodeResponse.SerializeToString,
            ),
            'GetEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdge,
                    request_deserializer=cyrock__db__graph__pb2.GetEdgeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetEdgeResponse.SerializeToString,
            ),
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=cyrock__db__graph__pb2.AddNodeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.AddNodeResponse.SerializeToString,
            ),
            'AddEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdge,
                    request_deserializer=cyrock__db__graph__pb2.AddEdgeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.AddEdgeResponse.SerializeToString,
            ),
            'RemoveNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNode,
                    request_deserializer=cyrock__db__graph__pb2.RemoveNodeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'RemoveEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveEdge,
                    request_deserializer=cyrock__db__graph__pb2.RemoveEdgeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'UpdateVector': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVector,
                    request_deserializer=cyrock__db__graph__pb2.UpdateVectorRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'UpdateWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWeight,
                    request_deserializer=cyrock__db__graph__pb2.UpdateWeightRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'UpdateNodeMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNodeMetadata,
                    request_deserializer=cyrock__db__graph__pb2.UpdateNodeMetadataRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'UpdateEdgeMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEdgeMetadata,
                    request_deserializer=cyrock__db__graph__pb2.UpdateEdgeMetadataRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=cyrock__db__graph__pb2.ListNodesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.ListNodesResponse.SerializeToString,
            ),
            'ListLabels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLabels,
                    request_deserializer=cyrock__db__graph__pb2.ListLabelsRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.ListLabelsResponse.SerializeToString,
            ),
            'SearchSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilar,
                    request_deserializer=cyrock__db__graph__pb2.SearchSimilarRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.SearchSimilarResponse.SerializeToString,
            ),
            'Neighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.Neighbors,
                    request_deserializer=cyrock__db__graph__pb2.NeighborsRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.NeighborsResponse.SerializeToString,
            ),
            'BatchNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchNeighbors,
                    request_deserializer=cyrock__db__graph__pb2.BatchNeighborsRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.BatchNeighborsResponse.SerializeToString,
            ),
            'Traverse': grpc.unary_unary_rpc_method_handler(
                    servicer.Traverse,
                    request_deserializer=cyrock__db__graph__pb2.TraverseRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.TraverseResponse.SerializeToString,
            ),
            'ContextWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.ContextWindow,
                    request_deserializer=cyrock__db__graph__pb2.ContextWindowRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.ContextWindowResponse.SerializeToString,
            ),
            'ReasoningChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ReasoningChain,
                    request_deserializer=cyrock__db__graph__pb2.ReasoningChainRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.ReasoningChainResponse.SerializeToString,
            ),
            'DetectCommunities': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectCommunities,
                    request_deserializer=cyrock__db__graph__pb2.DetectCommunitiesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.DetectCommunitiesResponse.SerializeToString,
            ),
            'PutCommunitySummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.PutCommunitySummaries,
                    request_deserializer=cyrock__db__graph__pb2.PutCommunitySummariesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.PutCommunitySummariesResponse.SerializeToString,
            ),
            'GlobalSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalSearch,
                    request_deserializer=cyrock__db__graph__pb2.GlobalSearchRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GlobalSearchResponse.SerializeToString,
            ),
            'RefreshCommunities': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshCommunities,
                    request_deserializer=cyrock__db__graph__pb2.DetectCommunitiesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.RefreshCommunitiesResponse.SerializeToString,
            ),
            'CommunityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CommunityStatus,
                    request_deserializer=cyrock__db__graph__pb2.CommunityStatusRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.CommunityStatusResponse.SerializeToString,
            ),
            'GetCommunities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunities,
                    request_deserializer=cyrock__db__graph__pb2.GetCommunitiesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.DetectCommunitiesResponse.SerializeToString,
            ),
            'GetCommunityMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunityMembers,
                    request_deserializer=cyrock__db__graph__pb2.GetCommunityMembersRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetCommunityMembersResponse.SerializeToString,
            ),
            'GetCommunityAssignments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunityAssignments,
                    request_deserializer=cyrock__db__graph__pb2.GetCommunityAssignmentsRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetCommunityAssignmentsResponse.SerializeToString,
            ),
            'GetCommunitySummaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunitySummaries,
                    request_deserializer=cyrock__db__graph__pb2.GetCommunitySummariesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetCommunitySummariesResponse.SerializeToString,
            ),
            'EntityLink': grpc.unary_unary_rpc_method_handler(
                    servicer.EntityLink,
                    request_deserializer=cyrock__db__graph__pb2.EntityLinkRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.EntityLinkResponse.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=cyrock__db__graph__pb2.ObserveRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.ObserveResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=cyrock__db__graph__pb2.RecallRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.RecallResponse.SerializeToString,
            ),
            'Decay': grpc.unary_unary_rpc_method_handler(
                    servicer.Decay,
                    request_deserializer=cyrock__db__graph__pb2.DecayRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.DecayResponse.SerializeToString,
            ),
            'ExecuteStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStatement,
                    request_deserializer=cyrock__db__graph__pb2.ExecuteStatementRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.StatementResponse.SerializeToString,
            ),
            'MergeData': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeData,
                    request_deserializer=cyrock__db__graph__pb2.MergeGraphDataRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.MergeGraphDataResponse.SerializeToString,
            ),
            'ExecuteTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTransaction,
                    request_deserializer=cyrock__db__graph__pb2.ExecuteTransactionRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.ExecuteTransactionResponse.SerializeToString,
            ),
            'UpsertNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertNode,
                    request_deserializer=cyrock__db__graph__pb2.UpsertNodeRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.UpsertNodeResponse.SerializeToString,
            ),
            'GetNodeByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeByKey,
                    request_deserializer=cyrock__db__graph__pb2.GetNodeByKeyRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetNodeResponse.SerializeToString,
            ),
            'RemoveNodeByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNodeByKey,
                    request_deserializer=cyrock__db__graph__pb2.RemoveNodeByKeyRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GraphEmpty.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=cyrock__db__graph__pb2.GetNodesRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.GetNodesResponse.SerializeToString,
            ),
            'InducedSubgraph': grpc.unary_unary_rpc_method_handler(
                    servicer.InducedSubgraph,
                    request_deserializer=cyrock__db__graph__pb2.InducedSubgraphRequest.FromString,
                    response_serializer=cyrock__db__graph__pb2.InducedSubgraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.cyrock.db.data.server.GraphGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.cyrock.db.data.server.GraphGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphGrpcService(object):
    """─── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetNode',
            cyrock__db__graph__pb2.GetNodeRequest.SerializeToString,
            cyrock__db__graph__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetEdge',
            cyrock__db__graph__pb2.GetEdgeRequest.SerializeToString,
            cyrock__db__graph__pb2.GetEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/AddNode',
            cyrock__db__graph__pb2.AddNodeRequest.SerializeToString,
            cyrock__db__graph__pb2.AddNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/AddEdge',
            cyrock__db__graph__pb2.AddEdgeRequest.SerializeToString,
            cyrock__db__graph__pb2.AddEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/RemoveNode',
            cyrock__db__graph__pb2.RemoveNodeRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/RemoveEdge',
            cyrock__db__graph__pb2.RemoveEdgeRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/UpdateVector',
            cyrock__db__graph__pb2.UpdateVectorRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/UpdateWeight',
            cyrock__db__graph__pb2.UpdateWeightRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNodeMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/UpdateNodeMetadata',
            cyrock__db__graph__pb2.UpdateNodeMetadataRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEdgeMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/UpdateEdgeMetadata',
            cyrock__db__graph__pb2.UpdateEdgeMetadataRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/ListNodes',
            cyrock__db__graph__pb2.ListNodesRequest.SerializeToString,
            cyrock__db__graph__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLabels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/ListLabels',
            cyrock__db__graph__pb2.ListLabelsRequest.SerializeToString,
            cyrock__db__graph__pb2.ListLabelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/SearchSimilar',
            cyrock__db__graph__pb2.SearchSimilarRequest.SerializeToString,
            cyrock__db__graph__pb2.SearchSimilarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Neighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/Neighbors',
            cyrock__db__graph__pb2.NeighborsRequest.SerializeToString,
            cyrock__db__graph__pb2.NeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/BatchNeighbors',
            cyrock__db__graph__pb2.BatchNeighborsRequest.SerializeToString,
            cyrock__db__graph__pb2.BatchNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Traverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/Traverse',
            cyrock__db__graph__pb2.TraverseRequest.SerializeToString,
            cyrock__db__graph__pb2.TraverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContextWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/ContextWindow',
            cyrock__db__graph__pb2.ContextWindowRequest.SerializeToString,
            cyrock__db__graph__pb2.ContextWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReasoningChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/ReasoningChain',
            cyrock__db__graph__pb2.ReasoningChainRequest.SerializeToString,
            cyrock__db__graph__pb2.ReasoningChainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectCommunities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/DetectCommunities',
            cyrock__db__graph__pb2.DetectCommunitiesRequest.SerializeToString,
            cyrock__db__graph__pb2.DetectCommunitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutCommunitySummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/PutCommunitySummaries',
            cyrock__db__graph__pb2.PutCommunitySummariesRequest.SerializeToString,
            cyrock__db__graph__pb2.PutCommunitySummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GlobalSearch',
            cyrock__db__graph__pb2.GlobalSearchRequest.SerializeToString,
            cyrock__db__graph__pb2.GlobalSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshCommunities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/RefreshCommunities',
            cyrock__db__graph__pb2.DetectCommunitiesRequest.SerializeToString,
            cyrock__db__graph__pb2.RefreshCommunitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommunityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/CommunityStatus',
            cyrock__db__graph__pb2.CommunityStatusRequest.SerializeToString,
            cyrock__db__graph__pb2.CommunityStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunities',
            cyrock__db__graph__pb2.GetCommunitiesRequest.SerializeToString,
            cyrock__db__graph__pb2.DetectCommunitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunityMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunityMembers',
            cyrock__db__graph__pb2.GetCommunityMembersRequest.SerializeToString,
            cyrock__db__graph__pb2.GetCommunityMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunityAssignments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunityAssignments',
            cyrock__db__graph__pb2.GetCommunityAssignmentsRequest.SerializeToString,
            cyrock__db__graph__pb2.GetCommunityAssignmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunitySummaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetCommunitySummaries',
            cyrock__db__graph__pb2.GetCommunitySummariesRequest.SerializeToString,
            cyrock__db__graph__pb2.GetCommunitySummariesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EntityLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/EntityLink',
            cyrock__db__graph__pb2.EntityLinkRequest.SerializeToString,
            cyrock__db__graph__pb2.EntityLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/Observe',
            cyrock__db__graph__pb2.ObserveRequest.SerializeToString,
            cyrock__db__graph__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/Recall',
            cyrock__db__graph__pb2.RecallRequest.SerializeToString,
            cyrock__db__graph__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/Decay',
            cyrock__db__graph__pb2.DecayRequest.SerializeToString,
            cyrock__db__graph__pb2.DecayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/ExecuteStatement',
            cyrock__db__graph__pb2.ExecuteStatementRequest.SerializeToString,
            cyrock__db__graph__pb2.StatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/MergeData',
            cyrock__db__graph__pb2.MergeGraphDataRequest.SerializeToString,
            cyrock__db__graph__pb2.MergeGraphDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/ExecuteTransaction',
            cyrock__db__graph__pb2.ExecuteTransactionRequest.SerializeToString,
            cyrock__db__graph__pb2.ExecuteTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/UpsertNode',
            cyrock__db__graph__pb2.UpsertNodeRequest.SerializeToString,
            cyrock__db__graph__pb2.UpsertNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetNodeByKey',
            cyrock__db__graph__pb2.GetNodeByKeyRequest.SerializeToString,
            cyrock__db__graph__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNodeByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/RemoveNodeByKey',
            cyrock__db__graph__pb2.RemoveNodeByKeyRequest.SerializeToString,
            cyrock__db__graph__pb2.GraphEmpty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/GetNodes',
            cyrock__db__graph__pb2.GetNodesRequest.SerializeToString,
            cyrock__db__graph__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InducedSubgraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.GraphGrpcService/InducedSubgraph',
            cyrock__db__graph__pb2.InducedSubgraphRequest.SerializeToString,
            cyrock__db__graph__pb2.InducedSubgraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
