# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyrock_db_data_pb2 as cyrock__db__data__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cyrock_db_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentGrpcServiceStub(object):
    """─── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upsert = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/Upsert',
                request_serializer=cyrock__db__data__pb2.UpsertDocumentRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.UpsertDocumentResponse.FromString,
                _registered_method=True)
        self.UpsertBatch = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/UpsertBatch',
                request_serializer=cyrock__db__data__pb2.UpsertDocumentsBatchRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.UpsertDocumentsBatchResponse.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/GetById',
                request_serializer=cyrock__db__data__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.DocumentProto.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/List',
                request_serializer=cyrock__db__data__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.DocumentList.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/Delete',
                request_serializer=cyrock__db__data__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.DocumentProto.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/Search',
                request_serializer=cyrock__db__data__pb2.SearchDocumentsRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.MultiSearch = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/MultiSearch',
                request_serializer=cyrock__db__data__pb2.MultiSearchDocumentsRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/HybridSearch',
                request_serializer=cyrock__db__data__pb2.HybridSearchDocumentsRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.SearchDocumentsResponse.FromString,
                _registered_method=True)
        self.ExecuteTransaction = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/ExecuteTransaction',
                request_serializer=cyrock__db__data__pb2.ExecuteDocumentTransactionRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.ExecuteDocumentTransactionResponse.FromString,
                _registered_method=True)
        self.UpsertByKey = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/UpsertByKey',
                request_serializer=cyrock__db__data__pb2.UpsertByKeyRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.UpsertByKeyResponse.FromString,
                _registered_method=True)
        self.GetByKey = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/GetByKey',
                request_serializer=cyrock__db__data__pb2.GetByKeyRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.DocumentProto.FromString,
                _registered_method=True)
        self.RemoveByKey = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/RemoveByKey',
                request_serializer=cyrock__db__data__pb2.RemoveByKeyRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.DocumentProto.FromString,
                _registered_method=True)
        self.ExecuteStatement = channel.unary_unary(
                '/ai.cyrock.db.data.server.DocumentGrpcService/ExecuteStatement',
                request_serializer=cyrock__db__data__pb2.ExecuteCollectionStatementRequest.SerializeToString,
                response_deserializer=cyrock__db__data__pb2.CollectionStatementResponse.FromString,
                _registered_method=True)


class DocumentGrpcServiceServicer(object):
    """─── Service ───────────────────────────────────────────────────────────────────

    """

    def Upsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertByKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveByKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStatement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=cyrock__db__data__pb2.UpsertDocumentRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.UpsertDocumentResponse.SerializeToString,
            ),
            'UpsertBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertBatch,
                    request_deserializer=cyrock__db__data__pb2.UpsertDocumentsBatchRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.UpsertDocumentsBatchResponse.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=cyrock__db__data__pb2.GetDocumentRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.DocumentProto.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=cyrock__db__data__pb2.ListDocumentsRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.DocumentList.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cyrock__db__data__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.DocumentProto.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=cyrock__db__data__pb2.SearchDocumentsRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'MultiSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiSearch,
                    request_deserializer=cyrock__db__data__pb2.MultiSearchDocumentsRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=cyrock__db__data__pb2.HybridSearchDocumentsRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.SearchDocumentsResponse.SerializeToString,
            ),
            'ExecuteTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTransaction,
                    request_deserializer=cyrock__db__data__pb2.ExecuteDocumentTransactionRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.ExecuteDocumentTransactionResponse.SerializeToString,
            ),
            'UpsertByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertByKey,
                    request_deserializer=cyrock__db__data__pb2.UpsertByKeyRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.UpsertByKeyResponse.SerializeToString,
            ),
            'GetByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByKey,
                    request_deserializer=cyrock__db__data__pb2.GetByKeyRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.DocumentProto.SerializeToString,
            ),
            'RemoveByKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveByKey,
                    request_deserializer=cyrock__db__data__pb2.RemoveByKeyRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.DocumentProto.SerializeToString,
            ),
            'ExecuteStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStatement,
                    request_deserializer=cyrock__db__data__pb2.ExecuteCollectionStatementRequest.FromString,
                    response_serializer=cyrock__db__data__pb2.CollectionStatementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.cyrock.db.data.server.DocumentGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.cyrock.db.data.server.DocumentGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentGrpcService(object):
    """─── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/Upsert',
            cyrock__db__data__pb2.UpsertDocumentRequest.SerializeToString,
            cyrock__db__data__pb2.UpsertDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/UpsertBatch',
            cyrock__db__data__pb2.UpsertDocumentsBatchRequest.SerializeToString,
            cyrock__db__data__pb2.UpsertDocumentsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/GetById',
            cyrock__db__data__pb2.GetDocumentRequest.SerializeToString,
            cyrock__db__data__pb2.DocumentProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/List',
            cyrock__db__data__pb2.ListDocumentsRequest.SerializeToString,
            cyrock__db__data__pb2.DocumentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/Delete',
            cyrock__db__data__pb2.DeleteDocumentRequest.SerializeToString,
            cyrock__db__data__pb2.DocumentProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/Search',
            cyrock__db__data__pb2.SearchDocumentsRequest.SerializeToString,
            cyrock__db__data__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/MultiSearch',
            cyrock__db__data__pb2.MultiSearchDocumentsRequest.SerializeToString,
            cyrock__db__data__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/HybridSearch',
            cyrock__db__data__pb2.HybridSearchDocumentsRequest.SerializeToString,
            cyrock__db__data__pb2.SearchDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/ExecuteTransaction',
            cyrock__db__data__pb2.ExecuteDocumentTransactionRequest.SerializeToString,
            cyrock__db__data__pb2.ExecuteDocumentTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/UpsertByKey',
            cyrock__db__data__pb2.UpsertByKeyRequest.SerializeToString,
            cyrock__db__data__pb2.UpsertByKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/GetByKey',
            cyrock__db__data__pb2.GetByKeyRequest.SerializeToString,
            cyrock__db__data__pb2.DocumentProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveByKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/RemoveByKey',
            cyrock__db__data__pb2.RemoveByKeyRequest.SerializeToString,
            cyrock__db__data__pb2.DocumentProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.DocumentGrpcService/ExecuteStatement',
            cyrock__db__data__pb2.ExecuteCollectionStatementRequest.SerializeToString,
            cyrock__db__data__pb2.CollectionStatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
