# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cyrock_db_nlsearch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cyrock_db_nlsearch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cyrock_db_data_pb2 as cyrock__db__data__pb2
from . import cyrock_db_value_pb2 as cyrock__db__value__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63yrock_db_nlsearch.proto\x12\x18\x61i.cyrock.db.data.server\x1a\x14\x63yrock_db_data.proto\x1a\x15\x63yrock_db_value.proto\"\xbf\x01\n\x19NlSearchCollectionRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x14\n\x0cvector_field\x18\x03 \x01(\t\x12\x18\n\x0bmax_results\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12<\n\x06rerank\x18\x05 \x01(\x0b\x32,.ai.cyrock.db.data.server.RerankOptionsProtoB\x0e\n\x0c_max_results\"\xb5\x01\n\x14NlSearchGraphRequest\x12\x10\n\x08graph_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x14\n\x0cvector_field\x18\x03 \x01(\t\x12\x18\n\x0bmax_results\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12<\n\x06rerank\x18\x05 \x01(\x0b\x32,.ai.cyrock.db.data.server.RerankOptionsProtoB\x0e\n\x0c_max_results\"i\n\x12NlSearchMatchProto\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x38\n\x08metadata\x18\x03 \x01(\x0b\x32&.ai.cyrock.db.data.server.CyrockStruct\"\x84\x01\n\x15NlSearchResponseProto\x12=\n\x07matches\x18\x01 \x03(\x0b\x32,.ai.cyrock.db.data.server.NlSearchMatchProto\x12\x18\n\x10translated_query\x18\x02 \x01(\t\x12\x12\n\nquery_type\x18\x03 \x01(\t2\xff\x01\n\x13NlSearchGrpcService\x12x\n\x10SearchCollection\x12\x33.ai.cyrock.db.data.server.NlSearchCollectionRequest\x1a/.ai.cyrock.db.data.server.NlSearchResponseProto\x12n\n\x0bSearchGraph\x12..ai.cyrock.db.data.server.NlSearchGraphRequest\x1a/.ai.cyrock.db.data.server.NlSearchResponseProtoB\x1f\n\x1b\x61i.cyrock.db.proto.nlsearchP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cyrock_db_nlsearch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033ai.cyrock.db.proto.nlsearchP\001'
  _globals['_NLSEARCHCOLLECTIONREQUEST']._serialized_start=100
  _globals['_NLSEARCHCOLLECTIONREQUEST']._serialized_end=291
  _globals['_NLSEARCHGRAPHREQUEST']._serialized_start=294
  _globals['_NLSEARCHGRAPHREQUEST']._serialized_end=475
  _globals['_NLSEARCHMATCHPROTO']._serialized_start=477
  _globals['_NLSEARCHMATCHPROTO']._serialized_end=582
  _globals['_NLSEARCHRESPONSEPROTO']._serialized_start=585
  _globals['_NLSEARCHRESPONSEPROTO']._serialized_end=717
  _globals['_NLSEARCHGRPCSERVICE']._serialized_start=720
  _globals['_NLSEARCHGRPCSERVICE']._serialized_end=975
# @@protoc_insertion_point(module_scope)
