# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyrock_db_nlsearch_pb2 as cyrock__db__nlsearch__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cyrock_db_nlsearch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NlSearchGrpcServiceStub(object):
    """─── Service ────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchCollection = channel.unary_unary(
                '/ai.cyrock.db.data.server.NlSearchGrpcService/SearchCollection',
                request_serializer=cyrock__db__nlsearch__pb2.NlSearchCollectionRequest.SerializeToString,
                response_deserializer=cyrock__db__nlsearch__pb2.NlSearchResponseProto.FromString,
                _registered_method=True)
        self.SearchGraph = channel.unary_unary(
                '/ai.cyrock.db.data.server.NlSearchGrpcService/SearchGraph',
                request_serializer=cyrock__db__nlsearch__pb2.NlSearchGraphRequest.SerializeToString,
                response_deserializer=cyrock__db__nlsearch__pb2.NlSearchResponseProto.FromString,
                _registered_method=True)


class NlSearchGrpcServiceServicer(object):
    """─── Service ────────────────────────────────────────────────────────────────────

    """

    def SearchCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlSearchGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCollection,
                    request_deserializer=cyrock__db__nlsearch__pb2.NlSearchCollectionRequest.FromString,
                    response_serializer=cyrock__db__nlsearch__pb2.NlSearchResponseProto.SerializeToString,
            ),
            'SearchGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGraph,
                    request_deserializer=cyrock__db__nlsearch__pb2.NlSearchGraphRequest.FromString,
                    response_serializer=cyrock__db__nlsearch__pb2.NlSearchResponseProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.cyrock.db.data.server.NlSearchGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.cyrock.db.data.server.NlSearchGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NlSearchGrpcService(object):
    """─── Service ────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def SearchCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.NlSearchGrpcService/SearchCollection',
            cyrock__db__nlsearch__pb2.NlSearchCollectionRequest.SerializeToString,
            cyrock__db__nlsearch__pb2.NlSearchResponseProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.cyrock.db.data.server.NlSearchGrpcService/SearchGraph',
            cyrock__db__nlsearch__pb2.NlSearchGraphRequest.SerializeToString,
            cyrock__db__nlsearch__pb2.NlSearchResponseProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
