# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cyrock_db_cdc_pb2 as cyrock__db__cdc__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cyrock_db_cdc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChangeStreamGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchChanges = channel.unary_stream(
                '/ai.cyrock.db.data.server.cdc.ChangeStreamGrpcService/WatchChanges',
                request_serializer=cyrock__db__cdc__pb2.WatchRequest.SerializeToString,
                response_deserializer=cyrock__db__cdc__pb2.ChangeEvent.FromString,
                _registered_method=True)


class ChangeStreamGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WatchChanges(self, request, context):
        """Server-streaming: watch committed changes to one graph or collection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChangeStreamGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchChanges,
                    request_deserializer=cyrock__db__cdc__pb2.WatchRequest.FromString,
                    response_serializer=cyrock__db__cdc__pb2.ChangeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.cyrock.db.data.server.cdc.ChangeStreamGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.cyrock.db.data.server.cdc.ChangeStreamGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChangeStreamGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WatchChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.cyrock.db.data.server.cdc.ChangeStreamGrpcService/WatchChanges',
            cyrock__db__cdc__pb2.WatchRequest.SerializeToString,
            cyrock__db__cdc__pb2.ChangeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
